run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  # deprecated
  - scopelint
  - interfacer
  - golint
  - deadcode
  - nosnakecase
  - structcheck
  - ifshort
  - maligned
  - varcheck
  ############
  - exhaustivestruct
  - varnamelen
  - exhaustruct
  - execinquery
  - musttag
  - depguard