archives:
- format: binary
builds:
- dir: ./cmd
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w -X github.com/maksim-paskal/k8s-resources-cli/pkg/config.gitVersion={{.Version}}-{{.ShortCommit}}-{{.Timestamp}}
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'